# Generated by Django 4.2.1 on 2023-08-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_watch_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='price',
        ),
    ]
